# General
label: Agency
endpoint: http://localhost:3004
inbound-transport:
  - [http, 0.0.0.0, 3004]
outbound-transport: http

# Admin
admin: [0.0.0.0, 3005]
admin-insecure-mode: true

# Connections
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Mediation
# mediator-invitation: http://localhost:3002?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiOGRjY2NjOGUtYjJhZi00NjVmLTg1NzktOWIwMWRmY2EwYmMzIiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwOi8vbG9jYWxob3N0OjMwMDIiLCAicmVjaXBpZW50S2V5cyI6IFsiQXMyd3JzWmI0Zmh0V3N0amE2UWpGQTk1Z0wzd0pqNm9XeGtDeVlaaGlBOG4iXSwgImxhYmVsIjogIk1lZGlhdG9yIn0=

# Multi-tenancy
multitenant: true
multitenant-admin: true
jwt-secret: very secret secret

# Webhooks
# webhook-url: http://localhost:1080/agency

# Wallet
wallet-type: indy
wallet-name: IndyWallet2
wallet-key: IndyWallet2
auto-provision: true
recreate-wallet: true

### Ledger ###

# No Ledger
no-ledger: true
# BCovrin
# genesis-url: http://test.bcovrin.vonx.io/genesis
# Sovrin Builder Net
# genesis-url: https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_builder_genesis

# Debug
# log-level: DEBUG
