# General
label: External Mediator
endpoint: http://localhost:3006
inbound-transport:
  - [http, 0.0.0.0, 3006]
outbound-transport: http
no-ledger: true

# Admin
admin: [0.0.0.0, 3007]
admin-insecure-mode: true

# Connections
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Mediation
open-mediation: true
auto-send-keylist-update-in-requests: true
auto-send-keylist-update-in-create-invitation: true

# Webhooks
webhook-url: http://localhost:1080/external-mediator
